---
abstract: "Transform text to a \"url friendly\" string"
author:
  - 'Renato Cron <renato@aware.com.br>'
build_requires:
  Test::More: 0
  strict: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text2URI
requires:
  Moose: 0
  Text::Iconv: 0
version: 0.2
